"""Stable public surface of the decision module."""

from .analytics import (
    AnalyticsToken,
    DecisionAnalyticsAction,
    DecisionAnalyticsClientEvent,
    DecisionAnalyticsClientEventType,
    DecisionAnalyticsEvent,
    DecisionAnalyticsEventId,
    DecisionAnalyticsEventType,
    DecisionAnalyticsFunnel,
    DecisionAnalyticsPayload,
    DecisionAnalyticsSource,
    DecisionAnalyticsStatus,
)
from .requests import DecisionConstraintsUpdate, DecisionRefinementAnswer, ProgramCommand, ShortlistCommand, ShortlistRoleCommand, SuggestionDecisionCommand
from .results import (
    DecisionCandidatePartition,
    DecisionConstraintApplicability,
    DecisionConstraintDimension,
    DecisionConstraintOutcome,
    DecisionContextResult,
    DecisionDataCompleteness,
    DecisionMutationResult,
    DecisionRefinementResult,
    DecisionRefinementOption,
    DecisionRefinementQuestion,
    DecisionShortlistItem,
    DecisionSuggestion,
    DecisionSuggestionReasons,
    DecisionSuggestionsResult,
)
from ..domain.entities import AdmissionConstraints, DecisionContext, DecisionContextMetadata, DecisionSnapshot, DecisionState, ShortlistEntry
from ..domain.values import AdmissionGate, DecisionId, DecisionSourceKind, DecisionStatus, ShortlistEntryState, ShortlistRole
from ..repository.ports import (
    DecisionBindingOutcome,
    DecisionBindingPort,
    DecisionAnalyticsReader,
    DecisionAnalyticsWriter,
    DecisionContextRepository,
    ProgramCandidateSnapshot,
    ProgramCandidateSource,
)

__all__ = [
    "AnalyticsToken",
    "AdmissionConstraints",
    "AdmissionGate",
    "DecisionCandidatePartition",
    "DecisionConstraintApplicability",
    "DecisionConstraintDimension",
    "DecisionConstraintOutcome",
    "DecisionBindingOutcome",
    "DecisionBindingPort",
    "DecisionAnalyticsAction",
    "DecisionAnalyticsClientEvent",
    "DecisionAnalyticsClientEventType",
    "DecisionAnalyticsEvent",
    "DecisionAnalyticsEventId",
    "DecisionAnalyticsEventType",
    "DecisionAnalyticsFunnel",
    "DecisionAnalyticsPayload",
    "DecisionAnalyticsSource",
    "DecisionAnalyticsStatus",
    "DecisionAnalyticsReader",
    "DecisionAnalyticsWriter",
    "DecisionConstraintsUpdate",
    "DecisionContext",
    "DecisionContextMetadata",
    "DecisionContextRepository",
    "DecisionContextResult",
    "DecisionDataCompleteness",
    "DecisionId",
    "DecisionMutationResult",
    "DecisionRefinementAnswer",
    "DecisionRefinementResult",
    "DecisionRefinementOption",
    "DecisionRefinementQuestion",
    "DecisionShortlistItem",
    "DecisionSnapshot",
    "DecisionSourceKind",
    "DecisionState",
    "DecisionStatus",
    "DecisionSuggestion",
    "DecisionSuggestionReasons",
    "DecisionSuggestionsResult",
    "ProgramCommand",
    "ProgramCandidateSnapshot",
    "ProgramCandidateSource",
    "ShortlistCommand",
    "ShortlistEntry",
    "ShortlistEntryState",
    "ShortlistRole",
    "ShortlistRoleCommand",
    "SuggestionDecisionCommand",
]
