"""Stable public contracts of the analytics module."""

from .metrics import MetricAggregation, MetricDefinition, MetricDomain, MetricEntityType
from .public import (
    ActivitySignalCode,
    AssessmentSummary,
    ProgramProjection,
    ProjectionBuild,
    ProjectionDataQuality,
    ProjectionDataQualityStatus,
    ProjectionMaterializationStatus,
    ProjectionMetric,
    ProjectionMetricEvidence,
    ProjectionTimeline,
    ProjectionRunStatus,
    ProgramProjectionRun,
    WorkloadSummary,
)
from .results import AnalyticsResult, AnalyticsResultStatus, AnalyticsRow, MetricExplanation
from .semantic_predicate import (
    SemanticPredicate,
    SemanticPredicateEvidence,
    SemanticPredicateFailureReason,
    SemanticPredicatePort,
    SemanticPredicateRequest,
    SemanticPredicateResult,
    SemanticPredicateRow,
    SemanticPredicateStatus,
)

__all__ = [
    "ActivitySignalCode",
    "AssessmentSummary",
    "ProjectionDataQuality",
    "ProjectionDataQualityStatus",
    "ProjectionMaterializationStatus",
    "ProjectionBuild",
    "ProjectionMetric",
    "ProjectionMetricEvidence",
    "ProjectionTimeline",
    "ProjectionRunStatus",
    "ProgramProjectionRun",
    "ProgramProjection",
    "WorkloadSummary",
    "MetricAggregation",
    "MetricDefinition",
    "MetricDomain",
    "MetricEntityType",
    "AnalyticsResult",
    "AnalyticsResultStatus",
    "AnalyticsRow",
    "MetricExplanation",
    "SemanticPredicate",
    "SemanticPredicateEvidence",
    "SemanticPredicateFailureReason",
    "SemanticPredicatePort",
    "SemanticPredicateRequest",
    "SemanticPredicateResult",
    "SemanticPredicateRow",
    "SemanticPredicateStatus",
]
