"""Stable public contracts of the proftest module."""

from ..domain.entities import (
    ActivityCode,
    AdaptiveAnswer,
    AnswerStatus,
    Answer,
    AnswerSet,
    AntiInterest,
    Confidence,
    CurriculumEvidence,
    DistinctiveSubject,
    ProgramFingerprint,
    Question,
    QuestionBlock,
    QuestionComponentType,
    QuestionOption,
    QuestionStage,
    UserProfile,
)
from ..domain.profile import ProfileRefinement, ProfileScope, UserProfileSnapshot
from ..domain.adaptive import AdaptiveDimension, AdaptiveSelection, AdaptiveState, AdaptiveStatus, AdaptiveStopReason
from ..domain.questions import Questionnaire
from ..domain.sessions import AnalyticsEventId, AnalyticsEventType, PreliminaryProfile, PreliminaryTopic, ProftestAnalyticsEvent, ProftestAnswerSession, ProftestSessionView, SessionAnswer, SessionId, SessionProgress, SessionStatus
from ..domain.capabilities import ProgramSignal, SourceCapability, source_capabilities
from ..domain.results import EvidenceMetric, EvidenceSignal, EvidenceStatus, MatchReason, MatchScore, MetricStatus, OptionalMetric, PreviewCandidate, ProftestPreview, ProftestResults, ReasonKind, Recommendation, RecommendationEvidence, ScoreBreakdown, SourceFreshness
from ..repository.ports import CurrentUserProfileReader, ProfileBindingOutcome, ProfileBindingPort, ProftestSessionBindingPort, UserProfileRefinementWriter

__all__ = [
    "ActivityCode",
    "AdaptiveDimension",
    "AdaptiveAnswer",
    "AdaptiveSelection",
    "AdaptiveState",
    "AdaptiveStatus",
    "AdaptiveStopReason",
    "Answer",
    "AnswerStatus",
    "AnswerSet",
    "AntiInterest",
    "AnalyticsEventId",
    "AnalyticsEventType",
    "Confidence",
    "CurriculumEvidence",
    "DistinctiveSubject",
    "EvidenceMetric",
    "EvidenceSignal",
    "EvidenceStatus",
    "MatchReason",
    "MatchScore",
    "MetricStatus",
    "OptionalMetric",
    "PreviewCandidate",
    "ProgramFingerprint",
    "ProftestPreview",
    "ProftestResults",
    "Question",
    "QuestionBlock",
    "QuestionComponentType",
    "QuestionOption",
    "QuestionStage",
    "Questionnaire",
    "ReasonKind",
    "Recommendation",
    "RecommendationEvidence",
    "CurrentUserProfileReader",
    "ProfileBindingOutcome",
    "ProfileBindingPort",
    "ProftestSessionBindingPort",
    "PreliminaryProfile",
    "PreliminaryTopic",
    "ProfileScope",
    "ProfileRefinement",
    "ProftestAnalyticsEvent",
    "ProftestAnswerSession",
    "ProftestSessionView",
    "ProgramSignal",
    "SourceCapability",
    "source_capabilities",
    "ScoreBreakdown",
    "SourceFreshness",
    "SessionId",
    "SessionAnswer",
    "SessionProgress",
    "SessionStatus",
    "UserProfile",
    "UserProfileSnapshot",
    "UserProfileRefinementWriter",
]
