import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

function argumentValue(name) {
  const index = process.argv.indexOf(name);
  if (index < 0) return undefined;
  const value = process.argv[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`${name} requires a value`);
  return value;
}

const sourceFile = process.env.OPENAPI_FILE ?? argumentValue("--spec");
const sourceUrl = process.env.OPENAPI_URL ?? "http://127.0.0.1:8000/openapi.json";
const response = sourceFile ? undefined : await fetch(sourceUrl);
if (response && !response.ok) throw new Error(`OpenAPI request failed with ${response.status}`);
const schema = sourceFile
  ? JSON.parse(await readFile(resolve(sourceFile), "utf8"))
  : await response.json();
const ast = await openapiTS(schema);
const output = `/* Generated by scripts/generate-api.mjs. Do not edit. */\n\n${astToString(ast)}`;
const outputPath = resolve(
  process.env.API_TYPES_OUTPUT ?? argumentValue("--output") ?? "src/lib/generated.ts",
);
await writeFile(outputPath, output, "utf8");
console.log(`Generated ${outputPath} from ${sourceFile ?? sourceUrl}`);
