"""Public shared contracts; domain modules own their subject-specific types."""

from .base import ContractModel
from .enums import AssessmentType, CompareStatus, ComparisonScope, EducationLevel, SourceKind
from .errors import (
    AndromedaError,
    ContractError,
    ConflictError,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    NotFoundError,
    ValidationError,
)
from .ids import (
    Credits,
    CurriculumId,
    CurriculumItemId,
    DepartmentId,
    DirectionCode,
    DirectionId,
    DisciplineId,
    EducationYear,
    EventId,
    HourCount,
    NonEmptyText,
    ProgramCode,
    ProgramId,
    ShortText,
    SourceHash,
    SourcePosition,
    Semester,
    UniversityId,
    VenueId,
)
from .provenance import GapSeverity, SourceAttribution, SourceGapReference

__all__ = [
    "AndromedaError",
    "AssessmentType",
    "CompareStatus",
    "ComparisonScope",
    "ContractError",
    "ConflictError",
    "ContractModel",
    "Credits",
    "CurriculumId",
    "CurriculumItemId",
    "DepartmentId",
    "DirectionCode",
    "DirectionId",
    "DisciplineId",
    "EducationLevel",
    "GapSeverity",
    "EventId",
    "EducationYear",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "HourCount",
    "NonEmptyText",
    "NotFoundError",
    "ProgramCode",
    "ProgramId",
    "ShortText",
    "SourceHash",
    "SourcePosition",
    "Semester",
    "SourceAttribution",
    "SourceGapReference",
    "SourceKind",
    "ValidationError",
    "UniversityId",
    "VenueId",
]
