import { escapeHtml, safeHttpUrl } from '../dom.js';

export function renderProgramCard(program, { saved = false, compared = false, showActions = true } = {}) {
  if (program.sourceBacked) {
    const planYear = program.educationYear ? `Учебный план ${escapeHtml(program.educationYear)} года` : 'План обучения';
    const sourceUrl = safeHttpUrl(program.provenance?.sourceUrl || program.sourceUrl);
    return `<article class="program-card"><div class="program-meta"><span class="code">${escapeHtml(program.code)}</span><button class="heart ${saved ? 'saved' : ''}" data-save="${escapeHtml(program.id)}" title="${saved ? 'Убрать из подборки' : 'Добавить в подборку'}">${saved ? '♥' : '♡'}</button></div><div class="uni">${escapeHtml(program.universityName || program.university || 'Вуз не указан в источнике')}</div><h3>${escapeHtml(program.name || program.title)}</h3><p class="muted small">${planYear}${sourceUrl ? ` · <a href="${escapeHtml(sourceUrl)}" target="_blank" rel="noopener noreferrer">Источник</a>` : ''}</p>${showActions ? `<div class="card-actions"><button class="btn btn-outline btn-sm" data-page="program" data-program="${escapeHtml(program.id)}">Подробнее</button><button class="btn ${compared ? 'btn-outline' : 'btn-primary'} btn-sm" data-compare-toggle="${escapeHtml(program.id)}" aria-pressed="${compared}">${compared ? 'Убрать' : 'Сравнить'}</button></div>` : ''}</article>`;
  }
  const cost = Number.isFinite(Number(program.cost)) && program.cost !== null ? `${Math.round(Number(program.cost) / 1000)}к` : '—';
  return `<article class="program-card"><div class="program-meta"><span class="code">${escapeHtml(program.code)}</span><button class="heart ${saved ? 'saved' : ''}" data-save="${escapeHtml(program.id)}" title="${saved ? 'Убрать из shortlist' : 'Добавить в shortlist'}">${saved ? '♥' : '♡'}</button></div><div class="uni">${escapeHtml(program.university)}</div><h3>${escapeHtml(program.title)}</h3><div class="tags">${program.areas.map((area) => `<span class="tag">${escapeHtml(area)}</span>`).join('')}</div><div class="program-facts"><div><b>${escapeHtml(program.passing ?? '—')}</b><span>проходной</span></div><div><b>${escapeHtml(program.budget ?? '—')}</b><span>мест</span></div><div><b>${cost}</b><span>стоимость</span></div></div>${showActions ? `<div class="card-actions"><button class="btn btn-outline btn-sm" data-page="program" data-program="${escapeHtml(program.id)}">Подробнее</button><button class="btn ${compared ? 'btn-outline' : 'btn-primary'} btn-sm" data-compare-toggle="${escapeHtml(program.id)}" aria-pressed="${compared}" aria-label="${compared ? 'Убрать из сравнения' : 'Добавить в сравнение'}" title="${compared ? 'Убрать из сравнения' : 'Добавить в сравнение'}">${compared ? 'Убрать' : 'Сравнить'}</button></div>` : ''}</article>`;
}
